services:
  web:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_NODE_ENV=development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: bun run dev

  api:
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app
      - /app/node_modules
      - ./.env:/app/.env
    command: bun run dev

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
